class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'mirror6'
        self.UnzipMirrorCommand = 'unzipmirror6'
        self.TarMirrorCommand = 'tarmirror6'
        self.CancelMirror = 'cancel'
        self.CancelAllCommand = 'cancelall'
        self.ListCommand = 'list'
        self.StatusCommand = 'status'
        self.AuthorizeCommand = 'authorize'
        self.UnAuthorizeCommand = 'unauthorize'
        self.AuthListCommand = 'authlist'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'help'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest'
        self.CloneCommand = 'clone6'
        self.WatchCommand = 'watch6'
        self.TarWatchCommand = 'tarwatch6'
        self.DeleteCommand = 'del'
        self.UsageCommand = 'usage'
        self.RepoCommand = 'repo27'

BotCommands = _BotCommands()
